// =========================================================
// 🔒 SECRETS CONFIGURATION
// =========================================================

// --- 1. WIFI CONFIGURATION ---
// Enter your home WiFi network name (SSID) and password below.
// The ESP32 needs this to connect to the internet and send data.
const char* ssid = "YOUR_WIFI_NAME_HERE";
const char* password = "YOUR_WIFI_PASSWORD_HERE";

// --- 2. GOOGLE SHEETS CONFIGURATION ---
// The Web App URL generated by your Google Apps Script deployment.
// To get this: Go to Apps Script -> Deploy -> New Deployment -> Web App.
// It MUST start with "https://script.google.com/macros/s/" and end with "/exec"
const char* GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/YOUR_SCRIPT_ID_HERE/exec";
